WEAPON_NAMES = ["Sword", "Pike", "Mace", "Axe"]

# roll_min, roll_max, rarity, damage_min, damage_max
WEAPON_ROLL_TABLE_DEFAULT = [
    (0, 0, "God", 19, 24),
    (1, 75, "Normal", 5, 10),
    (76, 92, "Rare", 9, 15),
    (93, 100, "Legendary", 13, 19),
]

WEAPON_ROLL_TABLE_BOSS = [
    (0, 9, "God", 22, 28),
    (10, 44, "Legendary", 16, 23),
    (45, 79, "Rare", 12, 18),
    (80, 100, "Normal", 8, 13),
]

STARTING_WEAPON_DAMAGE_MIN = 5
STARTING_WEAPON_DAMAGE_MAX = 10
STARTING_WEAPON_RARITY = "Normal"

BASE_POINTS = 5
BASE_WARRIOR_MAX_HP = 37
BASE_WARRIOR_MAX_SP = 15
BASE_WARRIOR_ARMOR = 1
BASE_WARRIOR_ATTACK = 2

ESCAPE_SP_COST = 10
ESCAPE_MIN_SP_REQUIRED = 13
ESCAPE_SUCCESS_ROLL_MAX = 35

DEFAULT_INVENTORY_SIZE = 6

STARTING_HEALTH_POTION_HEAL = 15
STARTING_STAMINA_POTION_RECOVERY = 10
STARTING_HEALTH_POTION_QUANTITY = 2
STARTING_STAMINA_POTION_QUANTITY = 1
